- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: mahendra3/calculator:latest
        source: pull

    - name: Check if container exists
      shell: docker ps -a --filter "name=Calculator" --format "{{'{{'}}.Names{{'}}'}}"
      register: container_check
      ignore_errors: yes

    - name: Stop container
      shell: docker stop Calculator
      when: container_check.stdout == "Calculator"

    - name: Remove container
      shell: docker rm Calculator
      when: container_check.stdout == "Calculator"

    - name: Running container
      shell: docker run -it -d --name Calculator mahendra3/calculator:latest
